name: Node.js CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and run containers
      run: docker-compose up -d

    - name: Wait for database to be ready
      run: |
        while ! docker exec cosc310-mysql mysqladmin --user=root --password=rootpw --host "127.0.0.1" ping --silent &> /dev/null ; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Run tests
      run: docker exec cosc310-node npm test

    - name: Clean up
      run: docker-compose down
